### ISSUE TITLE
ModuleNotFoundError: No module named 'ipwhois.net'

### ISSUE THREAD

**Issue by changtraisitinh** [t4d/StalkPhish#17]
please help me about error ?

```
# pip3 install -r requirements.txt
# pip install ipwhois
root@kali:~/Tools/StalkPhish/stalkphish# python3 StalkPhish.py 
Traceback (most recent call last):
  File "StalkPhish.py", line 26, in <module>
    from tools.utils import VerifyPath
  File "/root/Tools/StalkPhish/stalkphish/tools/utils.py", line 13, in <module>
    from ipwhois.net import Net
ModuleNotFoundError: No module named 'ipwhois.net'
```

**Comment by t4d** [comment]
Hi! There's sometimes problems between pip installed and system installed packages, or it could be a conflict with different python's whois libs.
You should test in a virtual-environment :
` $ python3 -m venv virt-env`
` $ . ./virt-env/bin/activate`

**Comment by t4d** [comment]
Is it ok for you? Can I close this issue?
