### ISSUE TITLE
ImportError: No module named 'ipwhois'

### ISSUE THREAD

**Issue by BrickBross** [t4d/StalkPhish#25]
Hi,

Not sure if i am missing something here,

Running on Ubuntu Server 16.04,

When try run i get the following

Traceback (most recent call last):
  File "./StalkPhish.py", line 26, in <module>
    from tools.utils import VerifyPath
  File "/home/[username]/StalkPhish/stalkphish/tools/utils.py", line 13, in <module>
    from ipwhois.net import Net
ImportError: No module named 'ipwhois'

When i look in the modules i dont see anything for ipwhois. I can comment this out in the utils.py to work but then clearly i wont get the ipwhois data

Cheers

**Comment by BrickBross** [comment]
Hi,

To add to this it looks like it gets to the end of the keyword search and then i get the following;

2020-01-27 14:52:54,450 - StalkPhish.py - ERROR - Main error (<class 'ImportError'>, ImportError("No module named 'cfscrape'",), <traceback object at 0x7f30698c0b08>)

Apologies if this is just a misconfiguration on my side

Cheers

**Comment by BrickBross** [comment]
Please ignore - this was my error, i just noticed the pip install of the requirements never ran!
